# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "optimizations-ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on Xcode ${{ matrix.xcode }}
    runs-on: ${{ matrix.runs-on }}
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer"
    strategy:
      fail-fast: false
      matrix:
        include:
          - swift: "5.9"
            xcode: "15.2"
            runs-on: macos-14
          - swift: "5.10"
            xcode: "15.4"
            runs-on: macos-14
          - swift: "6.0"
            xcode: "16.0"
            runs-on: macos-15
          - swift: "6.1"
            xcode: "16.3"
            runs-on: macos-15
    

    steps:
    - uses: actions/checkout@v4

    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift }}

    - name: Install swift-format
      run: brew install swift-format

    - name: Run swift-format
      run: swift-format lint --recursive . --strict

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
