# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on Xcode ${{ matrix.xcode }}
    runs-on: ${{ matrix.runs-on }}
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer"
    strategy:
      fail-fast: false
      matrix:
        include:
          - swift: "6.0"
            xcode: "16.0"
            runs-on: macos-15
          - swift: "6.1"
            xcode: "16.3"
            runs-on: macos-15
    

    steps:
    - uses: actions/checkout@v4

    - name: Lint
      run: swift format lint --recursive . --strict

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
